name: Docker Build CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Docker image check
        run: |
          docker images
          
      - name: Build Docker image from Dockerfile
        run: |
          docker build -t npm-image .
          
      - name: Docker image check
        run: |
          docker images

      - name: Run container (test)
        run: |
          docker run --rm npm-image
          
      - name: Push Docker image
        run: |
          docker ps
