name: Docker Build CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Execution location
        run: pwd
        
      - name: Docker image check
        run: |
          docker images

      - name: Docker image build
        run: |
          docker build -t cpp-image:01 .

      - name: Docker image Check
        run: |
          docker images

      - name: Docker run container
        run: |
          docker run -d --rm name container1 cpp-image:01

      - name: docker container run
        run: | 
          docker ps -a
